=== huanStephen/winger/src/main/java/org/eocencle/winger/builder/xml/winger-1-response.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT response (branch* | sql*)+>
<!ATTLIST response
namespace CDATA #REQUIRED
>

<!ELEMENT json (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST json
id CDATA #REQUIRED
>

<!ELEMENT branch (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST branch
name CDATA #REQUIRED
type (GET | POST | PUT | DELETE) #IMPLIED width CDATA "GET"
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== huanStephen/winger/src/main/resource/response.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE response PUBLIC "-//www.eocencle.org//DTD Config 1.0//EN" "http://www.eocencle.org/winger/dtd/winger-1-response.dtd">
<response contextpath="winger/">
	<json id="result1">
		"say" : "hello wolrd"
	</json>
	<json id="result2">
		"speak" : "you are welcome ${value}"
	</json>
	<branch action="/item/addItem" method="post">
		{
			"meta" : {
				"code" : 1,
				"msg" : "请求成功！",
				"data" : "${value}"
			},
			"data" : {
				<if test="1 == id">
					<include refid="result1" />
				</if>
				<if test="2 == id">
					<include refid="result2" />
				</if>
			}
		}
	</branch>
</response>
